Name="杨可欣"
day_str="38.5"
print(Name)
print(float(day_str))
day_float=float(day_str)
day1_PF=day_float**2
print(f"{day_str}的平方是：{day1_PF}")
day_float1=38.5
print(f"{day_float1}的平方是：{day_float1**2}")